= JSA

:toc: preamble
:toclevels: 3
:version-label: s

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

An ipmitool wrapper.

It simplifies ipmitool invocation by,

* adding <<profile, profile>> support (a profile is a combination of any of hostname, username, password,
and interface),
* adding <<scripting, scripting>> support,
* adding some <<commands, built-in commands>> like autosol,
* <<jsa-ip-pref, auto completing IPv4 prefix>> in hostname, and maybe more in future.

toc::[]

== Usage

[,console]
----
jsa [<options>] <command> [<argument> ...]
----

<command>:: An IPMI command or a <<commands, built-in commands>>.
Use `jsa <command> --help` for usage on a specific built-in command.

-h, --help:: Print help and exit; can be used with commands
-V, --version:: Print version and exit
-H, --hostname HOSTNAME:: Remote host name for ipmitool commands.
-U, --username USERNAME:: Username of remote host for ipmitool commands.
-P, --password PASSWORD:: Password of remote host for ipmitool commands.
-I, --interface INTERFACE:: Interface for ipmitool commands.

-r, --profile PROFILE:: Load <<profile, profile>> from `profiles.toml`.
It has lower priority than -H, -U, -P, and -I.

--ipmitool-path IPMITOOL_PATH:: Path to ipmitool executable to be used this time only.
--ipmitool-help:: Show help information of ipmitool.
--dry-run:: Print the command and arguments that would be executed and exit.

== Features

[#profile]
=== Profile

A profile is a combination of any of hostname, username, password, and interface.
It's defined in file `profile.toml` located in the same directory with `jsa`.

Let's take the below content of `profile.toml` as an example:

[,toml]
----
[default]
username = "admin"
password = "admin"
interface = "lanplus"

[example]
hostname = "example.com"

[root]
username = "root"
password = "root"
----

The name in brackets (*default*, *example*, and *root* in this example) is the *profile name*.
The *default* profile is a special one -- it's always loaded, even when other profile is loaded, acting as a set
of fallback values.

With the above profile.toml, the below 3 commands are equivalent:

[,console]
----
jsa -r example mc info
jsa -H example.com mc info
ipmitool -H example.com -U admin -P admin -I lanplus mc info
----

Profile elements can be overridden by *-H*, *-U*, *-P*, and *-I*, so the below commands are equivalent:

[,console]
----
jsa -r root -H example.net -P newpass mc info
ipmitool -H example.net -U root -P newpass -I lanplus mc info
----

Except for *default* profile, only one profile can be used for a session.
If multiple profiles are specified, only the last one takes effect.  Below commands are equivalent:

[,console]
----
jsa -r root -r example mc info
jsa -r example mc info
ipmitool -H example.com -U admin -P admin -I lanplus mc info
----

[#commands]
=== Built-in Commands

Built-in commands are ones that added by jsa rather than ipmitool.

==== autosol

This command is a wrapper of ipmitool sol command, adding features such as logging.

[,console]
----
jsa [<jsa_options>] autosol [<option> ...]
----

-h, --help:: Show help message and exit.
--deactivate:: Deactivate previous possibly activated SOL session.  This is the default.
--no-deactivate:: Do not deactivate previous possibly activated SOL session
--power-off:: Perform power off. This is the default.
--no-power-off:: Do not perform power off, and disable `--sleep`.
--sleep SECONDS:: Time to sleep after performing power off.  Default is 10.0.
--power-on:: Perform power on.  This is the default.
--no-power-on:: Do not perform power on.
--log:: Save SOL output to file.  This is the default.  See also `--output`.
--no-log:: Do not save SOL output to file; this ignores `--output`.

-o, --output OUTPUT:: path of the log file for the SOL output (can be a directory).
$(hostname) will be replaced to actual hostname. Date and time format is the same with strftime.
(default: `autosol-$(hostname)-%Y%m%d-%H%M%S.log`)

-d, --deactivate-and-activate:: Shortcut for `--no-power-off` and `--no-power-on`
-a, --activate-only:: Shortcut for `--no-deactivate`, `--no-power-off`, and `--no-power-on`.

==== Sleep

Sleep certain second(s).
Designed to be used in <<scripting, scripting>>.
It prints a message like `Sleep 1.0 second(s)` to stdout unless `-q` is specified.

[,console]
----
jsa [<jsa_options>] sleep [<seconds>] [-q]
----

<seconds>:: The number of seconds to sleep, can be a float number.  Default is *1.0*.
-q, --queit, --silent:: Suppress all normal output.

==== Echo

Print its arguments to stdout.
An empty line will be printed if used without any argument.
Designed to be used in <<scripting, scripting>>.

[,console]
----
jsa [<jsa_options>] echo [...]
----

[#scripting]
=== Scripting

You can write a sequence of commmands to file `scripts/<name>.txt`, and execute them by `<name>`.

[,console]
----
jsa [<jsa_options>] <name> [<argument> ...]
----

<name>:: Script name without `.txt`.
<argument>:: Arguments passed to the script.  They can be refered by `$@` or `$1` in scripts.
See also <<script-arguments, Script Arguments>>.

==== Script Syntax

----
[!] <command> [<argument> ...]
...
----

Line `COMMAND ARGUMENT` will be executed as `jsa COMMAND ARGUMENT`.

Script content is executed line by line.
Unless prefixed with `!`, the script will abort on error.

==== Script Comments

Lines starting with `#` are comments and have no effect, as well as empty lines.
Note that `#` can only be at the first column of a line to make it a comment line.

[#script-arguments]
==== Script Arguments

Arguments passed to scripts can be refered by special notations.

$@, $*:: All arguments.  Currently `$@` and `$*` are equivalent.

$1, $2, ...:: The first argument.  Similarly, `$2` is the second argument.
The max number is up to the shell capacity.

$#:: The number of arguments.

[NOTE]
====
Place ipmitool options after the script name when running on command line,
because if not, the script name will be passed to ipmitool as one of arguments.

However, if you want to pass common flags (such as `-N1`) rather than command argument,
place the `$@` before the command in scripts.
====

[#jsa-ip-pref]
=== Hostname Auto Completion

A hostname can be either a domain name (www.example.com) or an IP address.

For IPv4 addresses, after set environment variable `JSA_IP_PREF` to a starting part, such as `192.168.1`,
you can specify the ending part of the IPv4 as hostname, such as `10` or `2.1`,
and the hostname will be combined from them, and become `192.168.1.10` or `192.168.2.1`.
