# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem 'jekyll'
gem 'logger'

gem 'just-the-docs'

group :jekyll_plugins do
  gem 'jekyll-seo-tag'
  gem 'jekyll-github-metadata'
  gem 'jekyll-include-cache'
  gem 'jekyll-sitemap'
end
